name: Tests
on:
  repository_dispatch:
    types: [tests-report]
  push:
jobs:
  unit-tests:
    name: Unit tests
    strategy:
      matrix:
        platform: [ubuntu-latest]  # , windows-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    env:
      RUST_BACKTRACE: 1
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      - name: Run integration test
        run: cd integration-tests && cargo run --example integration-tests
      - name: Market tests
        run: cd market-contract && cargo test
      - name: Contract Basics tests        
        run: cd nft-contract-basic && cargo test
      - name: Events tests        
        run: cd nft-contract-events && cargo test
      - name: Royalty tests        
        run: cd nft-contract-royalty && cargo test
      - name: Skeleton tests        
        run: cd nft-contract-skeleton && cargo test
      - name: NFT series tests        
        run: cd nft-series && cargo test        
